[ydict]
src.github = "TimothyYe/ydict"
fetch.github = "TimothyYe/ydict"

[f2]
src.github = "ayoisaiah/f2"
fetch.github = "ayoisaiah/f2"

[clash-verge]
src.github = "zzzgydi/clash-verge"
fetch.github = "zzzgydi/clash-verge"

[dialect]
src.github = "dialect-app/dialect"
fetch.github = "dialect-app/dialect"
